<?php

namespace Database\Seeders;

use App\Models\Keuangan;
use App\Models\User;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class KeuanganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Find the first user with the role 'Ketua RT' and get the associated penduduk_id
        $user = User::with('penduduk')
            ->whereHas('role', function ($query) {
                $query->where('role_name', 'Ketua RT');
            })
            ->first();

        if ($user && $user->penduduk) {
            $penduduk_id = $user->penduduk->penduduk_id;

            $data = [
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 20000,
                    'tanggal' => Carbon::parse('2024-01-05'),
                    'created_at' => Carbon::parse('2024-01-05'),
                    'updated_at' => Carbon::parse('2024-01-05'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 25000,
                    'tanggal' => Carbon::parse('2024-01-10'),
                    'created_at' => Carbon::parse('2024-01-10'),
                    'updated_at' => Carbon::parse('2024-01-10'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 100000,
                    'tanggal' => Carbon::parse('2024-01-15'),
                    'created_at' => Carbon::parse('2024-01-15'),
                    'updated_at' => Carbon::parse('2024-01-15'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 200000,
                    'tanggal' => Carbon::parse('2024-01-20'),
                    'created_at' => Carbon::parse('2024-01-20'),
                    'updated_at' => Carbon::parse('2024-01-20'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 350000,
                    'tanggal' => Carbon::parse('2024-01-25'),
                    'created_at' => Carbon::parse('2024-01-25'),
                    'updated_at' => Carbon::parse('2024-01-25'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 300000,
                    'tanggal' => Carbon::parse('2024-01-30'),
                    'created_at' => Carbon::parse('2024-01-30'),
                    'updated_at' => Carbon::parse('2024-01-30'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 150000,
                    'tanggal' => Carbon::parse('2024-02-05'),
                    'created_at' => Carbon::parse('2024-02-05'),
                    'updated_at' => Carbon::parse('2024-02-05'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 450000,
                    'tanggal' => Carbon::parse('2024-02-10'),
                    'created_at' => Carbon::parse('2024-02-10'),
                    'updated_at' => Carbon::parse('2024-02-10'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 500000,
                    'tanggal' => Carbon::parse('2024-02-15'),
                    'created_at' => Carbon::parse('2024-02-15'),
                    'updated_at' => Carbon::parse('2024-02-15'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 600000,
                    'tanggal' => Carbon::parse('2024-02-20'),
                    'created_at' => Carbon::parse('2024-02-20'),
                    'updated_at' => Carbon::parse('2024-02-20'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 700000,
                    'tanggal' => Carbon::parse('2024-02-25'),
                    'created_at' => Carbon::parse('2024-02-25'),
                    'updated_at' => Carbon::parse('2024-02-25'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 800000,
                    'tanggal' => Carbon::parse('2024-03-05'),
                    'created_at' => Carbon::parse('2024-03-05'),
                    'updated_at' => Carbon::parse('2024-03-05'),
                ],
                [
                    'penduduk_id' => $penduduk_id,
                    'total_keuangan' => 900000,
                    'tanggal' => Carbon::parse('2024-03-10'),
                    'created_at' => Carbon::parse('2024-03-10'),
                    'updated_at' => Carbon::parse('2024-03-10'),
                ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1000000,
                        'tanggal' => Carbon::parse('2024-03-15'),
                        'created_at' => Carbon::parse('2024-03-15'),
                        'updated_at' => Carbon::parse('2024-03-15'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1100000,
                        'tanggal' => Carbon::parse('2024-03-20'),
                        'created_at' => Carbon::parse('2024-03-20'),
                        'updated_at' => Carbon::parse('2024-03-20'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1200000,
                        'tanggal' => Carbon::parse('2024-03-25'),
                        'created_at' => Carbon::parse('2024-03-25'),
                        'updated_at' => Carbon::parse('2024-03-25'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1300000,
                        'tanggal' => Carbon::parse('2024-03-30'),
                        'created_at' => Carbon::parse('2024-03-30'),
                        'updated_at' => Carbon::parse('2024-03-30'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1400000,
                        'tanggal' => Carbon::parse('2024-04-05'),
                        'created_at' => Carbon::parse('2024-04-05'),
                        'updated_at' => Carbon::parse('2024-04-05'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1500000,
                        'tanggal' => Carbon::parse('2024-04-10'),
                        'created_at' => Carbon::parse('2024-04-10'),
                        'updated_at' => Carbon::parse('2024-04-10'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1600000,
                        'tanggal' => Carbon::parse('2024-04-15'),
                        'created_at' => Carbon::parse('2024-04-15'),
                        'updated_at' => Carbon::parse('2024-04-15'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1700000,
                        'tanggal' => Carbon::parse('2023-04-20'),
                        'created_at' => Carbon::parse('2023-04-20'),
                        'updated_at' => Carbon::parse('2023-04-20'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1800000,
                        'tanggal' => Carbon::parse('2023-04-25'),
                        'created_at' => Carbon::parse('2023-04-25'),
                        'updated_at' => Carbon::parse('2023-04-25'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 1900000,
                        'tanggal' => Carbon::parse('2023-04-30'),
                        'created_at' => Carbon::parse('2023-04-30'),
                        'updated_at' => Carbon::parse('2023-04-30'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2000000,
                        'tanggal' => Carbon::parse('2023-05-05'),
                        'created_at' => Carbon::parse('2023-05-05'),
                        'updated_at' => Carbon::parse('2023-05-05'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2100000,
                        'tanggal' => Carbon::parse('2023-05-10'),
                        'created_at' => Carbon::parse('2023-05-10'),
                        'updated_at' => Carbon::parse('2023-05-10'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2200000,
                        'tanggal' => Carbon::parse('2023-05-15'),
                        'created_at' => Carbon::parse('2023-05-15'),
                        'updated_at' => Carbon::parse('2023-05-15'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2300000,
                        'tanggal' => Carbon::parse('2023-05-20'),
                        'created_at' => Carbon::parse('2023-05-20'),
                        'updated_at' => Carbon::parse('2023-05-20'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2400000,
                        'tanggal' => Carbon::parse('2023-05-25'),
                        'created_at' => Carbon::parse('2023-05-25'),
                        'updated_at' => Carbon::parse('2023-05-25'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2500000,
                        'tanggal' => Carbon::parse('2023-05-30'),
                        'created_at' => Carbon::parse('2023-05-30'),
                        'updated_at' => Carbon::parse('2023-05-30'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2600000,
                        'tanggal' => Carbon::parse('2023-06-05'),
                        'created_at' => Carbon::parse('2023-06-05'),
                        'updated_at' => Carbon::parse('2023-06-05'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2700000,
                        'tanggal' => Carbon::parse('2023-06-10'),
                        'created_at' => Carbon::parse('2023-06-10'),
                        'updated_at' => Carbon::parse('2023-06-10'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2800000,
                        'tanggal' => Carbon::parse('2023-06-15'),
                        'created_at' => Carbon::parse('2023-06-15'),
                        'updated_at' => Carbon::parse('2023-06-15'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 2900000,
                        'tanggal' => Carbon::parse('2023-06-20'),
                        'created_at' => Carbon::parse('2023-06-20'),
                        'updated_at' => Carbon::parse('2023-06-20'),
                    ],                
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3000000,
                        'tanggal' => Carbon::parse('2023-06-25'),
                        'created_at' => Carbon::parse('2023-06-25'),
                        'updated_at' => Carbon::parse('2023-06-25'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3100000,
                        'tanggal' => Carbon::parse('2023-06-30'),
                        'created_at' =>Carbon::parse('2023-06-30'),
                        'updated_at' =>Carbon::parse('2023-06-30'),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3200000,
                        'tanggal' => Carbon::parse('2023-07-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3300000,
                        'tanggal' => Carbon::parse('2023-07-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3400000,
                        'tanggal' => Carbon::parse('2023-07-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3500000,
                        'tanggal' => Carbon::parse('2023-07-20'),
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                    [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3600000,
                        'tanggal' => Carbon::parse('2023-07-25'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3700000,
                        'tanggal' => Carbon::parse('2023-07-30'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3800000,
                        'tanggal' => Carbon::parse('2023-08-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3900000,
                        'tanggal' => Carbon::parse('2023-08-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4000000,
                        'tanggal' => Carbon::parse('2023-08-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4100000,
                        'tanggal' => Carbon::parse('2023-08-20'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4200000,
                        'tanggal' => Carbon::parse('2023-08-25'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4300000,
                        'tanggal' => Carbon::parse('2023-08-30'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4400000,
                        'tanggal' => Carbon::parse('2023-09-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4500000,
                        'tanggal' => Carbon::parse('2023-09-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4600000,
                        'tanggal' => Carbon::parse('2023-09-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4700000,
                        'tanggal' => Carbon::parse('2023-09-20'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4800000,
                        'tanggal' => Carbon::parse('2023-09-25'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4900000,
                        'tanggal' => Carbon::parse('2023-09-30'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5000000,
                        'tanggal' => Carbon::parse('2023-10-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5100000,
                        'tanggal' => Carbon::parse('2023-10-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5200000,
                        'tanggal' => Carbon::parse('2023-10-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5300000,
                        'tanggal' => Carbon::parse('2023-10-20'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5400000,
                        'tanggal' => Carbon::parse('2023-10-25'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5500000,
                        'tanggal' => Carbon::parse('2023-10-30'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5600000,
                        'tanggal' => Carbon::parse('2023-11-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5700000,
                        'tanggal' => Carbon::parse('2023-11-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5800000,
                        'tanggal' => Carbon::parse('2023-11-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3600000,
                        'tanggal' => Carbon::parse('2023-07-25'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3700000,
                        'tanggal' => Carbon::parse('2023-07-30'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3800000,
                        'tanggal' => Carbon::parse('2023-08-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 3900000,
                        'tanggal' => Carbon::parse('2023-08-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4000000,
                        'tanggal' => Carbon::parse('2023-08-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4100000,
                        'tanggal' => Carbon::parse('2023-08-20'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4200000,
                        'tanggal' => Carbon::parse('2023-08-25'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4300000,
                        'tanggal' => Carbon::parse('2023-08-30'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4400000,
                        'tanggal' => Carbon::parse('2023-09-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4500000,
                        'tanggal' => Carbon::parse('2023-09-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4600000,
                        'tanggal' => Carbon::parse('2023-09-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4700000,
                        'tanggal' => Carbon::parse('2023-09-20'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4800000,
                        'tanggal' => Carbon::parse('2023-09-25'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 4900000,
                        'tanggal' => Carbon::parse('2023-09-30'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5000000,
                        'tanggal' => Carbon::parse('2023-10-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5100000,
                        'tanggal' => Carbon::parse('2023-10-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5200000,
                        'tanggal' => Carbon::parse('2023-10-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5300000,
                        'tanggal' => Carbon::parse('2023-10-20'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5400000,
                        'tanggal' => Carbon::parse('2023-10-25'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5500000,
                        'tanggal' => Carbon::parse('2023-10-30'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5600000,
                        'tanggal' => Carbon::parse('2023-11-05'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5700000,
                        'tanggal' => Carbon::parse('2023-11-10'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                        'penduduk_id' => $penduduk_id,
                        'total_keuangan' => 5800000,
                        'tanggal' => Carbon::parse('2023-11-15'),
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 5900000,
                            'tanggal' => Carbon::parse('2023-11-20'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6000000,
                            'tanggal' => Carbon::parse('2023-11-25'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6100000,
                            'tanggal' => Carbon::parse('2023-11-30'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6200000,
                            'tanggal' => Carbon::parse('2023-12-05'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6300000,
                            'tanggal' => Carbon::parse('2023-12-10'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6400000,
                            'tanggal' => Carbon::parse('2023-12-15'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6500000,
                            'tanggal' => Carbon::parse('2023-12-20'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6600000,
                            'tanggal' => Carbon::parse('2023-12-25'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6700000,
                            'tanggal' => Carbon::parse('2023-12-30'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6800000,
                            'tanggal' => Carbon::parse('2024-01-05'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 6900000,
                            'tanggal' => Carbon::parse('2024-01-10'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7000000,
                            'tanggal' => Carbon::parse('2024-01-15'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7100000,
                            'tanggal' => Carbon::parse('2024-01-20'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7200000,
                            'tanggal' => Carbon::parse('2024-01-25'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7300000,
                            'tanggal' => Carbon::parse('2024-01-30'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7400000,
                            'tanggal' => Carbon::parse('2024-02-05'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7500000,
                            'tanggal' => Carbon::parse('2024-02-10'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7600000,
                            'tanggal' => Carbon::parse('2024-02-15'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7700000,
                            'tanggal' => Carbon::parse('2024-02-20'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7800000,
                            'tanggal' => Carbon::parse('2024-02-25'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 7900000,
                            'tanggal' => Carbon::parse('2024-02-29'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8000000,
                            'tanggal' => Carbon::parse('2024-03-05'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8100000,
                            'tanggal' => Carbon::parse('2024-03-10'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8200000,
                            'tanggal' => Carbon::parse('2024-03-15'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8300000,
                            'tanggal' => Carbon::parse('2024-03-20'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                            [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8400000,
                            'tanggal' => Carbon::parse('2024-03-25'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8500000,
                            'tanggal' => Carbon::parse('2024-03-30'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8600000,
                            'tanggal' => Carbon::parse('2024-04-05'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8700000,
                            'tanggal' => Carbon::parse('2024-04-10'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8800000,
                            'tanggal' => Carbon::parse('2024-04-15'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 8900000,
                            'tanggal' => Carbon::parse('2024-04-20'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9000000,
                            'tanggal' => Carbon::parse('2024-04-25'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9100000,
                            'tanggal' => Carbon::parse('2024-04-30'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9200000,
                            'tanggal' => Carbon::parse('2024-05-05'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9300000,
                            'tanggal' => Carbon::parse('2024-05-10'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9400000,
                            'tanggal' => Carbon::parse('2024-05-15'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9500000,
                            'tanggal' => Carbon::parse('2024-05-20'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9600000,
                            'tanggal' => Carbon::parse('2024-05-25'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9700000,
                            'tanggal' => Carbon::parse('2024-05-30'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9800000,
                            'tanggal' => Carbon::parse('2024-06-05'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 9900000,
                            'tanggal' => Carbon::parse('2024-06-10'),
                            'created_at' => now(),
                            'updated_at' => now(),
                        ],
                        [
                            'penduduk_id' => $penduduk_id,
                            'total_keuangan' => 10000000,
                            'tanggal' => Carbon::parse('2024-06-15'),
                            'created_at' => now(),
                            'updated_at' => now(),               
                        ]
                     ];

            foreach ($data as $item) {
                Keuangan::create($item);
            }
        }
    }
}
